apiVersion: v1
kind: ServiceAccount
metadata:
  name: pods-creator
  namespace: elab-hpc
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-creator
  namespace: elab-hpc
rules:
  - apiGroups:
      - ""
    resources: ["pods", "services"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-pods-binding
  namespace: elab-hpc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-creator
subjects:
- kind: ServiceAccount
  name: pods-creator
  namespace: elab-hpc
