apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs-creator
  namespace: energylab
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: create-jobs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-creator
subjects:
- kind: ServiceAccount
  name: jobs-creator
  namespace: energylab
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jobs-creator
  namespace: energylab
rules:
  - apiGroups:
      - ""
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
